services:
  nginx-webdav:
    image: ghcr.io/fkropfhamer/docker-webdav:main
    container_name: webdav
    restart: unless-stopped
    ports:
      - "2234:80/tcp"
    volumes:
      - "/path/to/your/data:/media/data"
    environment:
      - USERNAME=<your-username>
      - PASSWORD=<your-password>

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
